### PR TITLE
fix boolean values for the events of the closing/opening

### PR DESCRIPTION
**Pull request by cedoor**
Hi peter, thank you for your tiny tool.

I found a problem in the opening and closing events of the colorPicker, specifically in the 'renderCallback' function, because undefined is considered false, and therefore within the if statement with toggled === false also it is including the pointer movement event.

### CODE REVIEW

**Comment by PitPik** [comment]
Hi @cedoor ,
thanks for your interest and your participation in tinyColorPicker.
Well, you're right, this is not the nicest solution (a bit hacky). The variable `toggled` in the `renderCallback` delivers false or true if closed or opened, so a boolean if toggled at all. I use booleans a lot as they need no memory (compared to strings) but your solution is way better understandable as mine. This is a bit of a dilemma for me here. I would actually like to just merge you changes into tinyColorPicker, as it works fine and makes it more understandable, but I don't know what happens to developers that use it already this way, and an update would break everything...
Your concern about "undefined is considered false" is not quite correct. undefined is falsey but not false. So if you say `toggled === false` everything works as expected:

``` javascript
if (toggled === true) {
    // just opened
} else if (toggled === false) {
    // just closed
} else {
    // pointer movement
}
```

but if you say:

``` javascript
if (toggled) {
    // just opened
} else if (!toggled) {
    // could be undefined or false... trouble!!!
} else {
    // will never happen
}
```

you'll get in big trouble ;o)

What do you think?

**Comment by cedoor** [comment]
Sorry, you are right, effectively using === works fine! Only could be misleading...
Another thing, i have a problem with doRender! If it remains active even when the colorPicker is hide it create me problems with set of the background-color of $elm. It's a normal thing?

**Comment by PitPik** [comment]
Hi @cedoor 
I don't quite understand the problem. Is it that `renderCallback` (with toggled === false) gets called even if the colorPicker is closed? If that's the case, I can fix this and make a new release.
If I just guessed wrong, let me know.

**Comment by PitPik** [comment]
New update available...

**Comment by cedoor** [comment]
Hi, not in if( toggled === false ) {...} but in else {...}, however the problem is fixed with the new update. 
Thanks!

**Comment by PitPik** [comment]
Good to hear!

Cheers

**Pull request closed without merging**
